### PR TITLE
177: use `num_elements` instead of `size`

### LINKED ISSUE #177: Can't compile models on a M3 Macbook Pro
This is on an M3 Mac

**To Reproduce**
``` r
library("primarycensored")
pcd_model <- pcd_cmdstan_model()
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:858:47: error: non-constant-expression cannot be narrowed from type 'size_t' (aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
#>   858 |         std::vector<int>{dist_id, primary_id, stan::math::size(params),
#>       |                                               ^~~~~~~~~~~~~~~~~~~~~~~~
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:944:18: note: in instantiation of function template specialization 'pcens_model_model_namespace::primarycensored_cdf<int, std::vector<double>, int, std::vector<double>, nullptr>' requested here
#>   944 |                  primarycensored_cdf(d, dist_id, params, pwindow,
#>       |                  ^
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:1028:21: note: in instantiation of function template specialization 'pcens_model_model_namespace::primarycensored_lcdf<int, std::vector<double>, int, std::vector<double>, nullptr>' requested here
#>  1028 |     log_cdf_upper = primarycensored_lcdf(d_upper, dist_id, params, pwindow,
#>       |                     ^
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:2813:15: note: in instantiation of function template specialization 'pcens_model_model_namespace::primarycensored_lpmf<false, int, std::vector<double>, int, std::vector<double>, nullptr>' requested here
#>  2813 |               primarycensored_lpmf<false>(
#>       |               ^
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:3257:12: note: in instantiation of function template specialization 'pcens_model_model_namespace::pcens_model_model::log_prob_impl<false, false, Eigen::Matrix<double, -1, 1>, Eigen::Matrix<int, -1, 1>, nullptr, nullptr, nullptr>' requested here
#>  3257 |     return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
#>       |            ^
#> /Users/eidesfun/.cmdstan/cmdstan-2.35.0/stan/src/stan/model/model_base_crtp.hpp:93:50: note: in instantiation of function template specialization 'pcens_model_model_namespace::pcens_model_model::log_prob<false, false, double>' requested here
#>    93 |     return static_cas
#> t<const M*>(this)->template log_prob<false, false, double>(
#>       |                                                  ^
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:2407:3: note: in instantiation of member function 'stan::model::model_base_crtp<pcens_model_model_namespace::pcens_model_model>::log_prob' requested here
#>  2407 |   ~pcens_model_model() {}
#>       |   ^
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:858:47: note: insert an explicit cast to silence this issue
#>   858 |         std::vector<int>{dist_id, primary_id, stan::math::size(params),
#>       |                                               ^~~~~~~~~~~~~~~~~~~~~~~~
#>       |                                               static_cast<int>(       )
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:859:11: error: non-constant-expression cannot be narrowed from type 'size_t' (aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
#>   859 |           stan::math::size(primary_params)}, "assigning variable ids");
#>       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:859:11: note: insert an explicit cast to silence this issue
#>   859 |           stan::math::size(primary_params)}, "assigning variable ids");
#>       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#>       |           static_cast<int>(               )
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:858:47: error: non-constant-expression cannot be narrowed from type 'size_t' (aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
#>   858 |         std::vector<int>{dist_id, primary_id, stan::math::size(params),
#>       |                                               ^~~~~~~~~~~~~~~~~~~~~~~~
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:944:18: note: in instantiation of function template specialization 'pcens_model_model_namespace::primarycensored_cdf<int, std::vector<stan::math::var_value<double>>, int, std::vector<stan::math::var_value<double>>, nullptr>' requested here
#>   944 |                  primarycensored_cdf(d, dist_id, params, pwindow,
#>       |                  ^
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:1028:21: note: in instantiation of function template specialization 'pcens_model_model_namespace::primarycensored_lcdf<int, std::vector<stan::math::var_value<double>>, int, std::vector<stan::math::var_value<double>>, nullptr>' requested here
#>  1028 |     log_cdf_upper = primarycensored_lcdf(d_upper, dist_id, params, pwindow,
#>       |                     ^
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:2928:15: note: in instantiation of function template specialization 'pcens_model_model_namespace::primarycensored_lpmf<false, int, std::vector<stan::math::var_value<double>>, int, std::vector<stan::math::var_value<double>>, nullptr>' requested here
#>  2928 |               primarycensored_lpmf<false>(
#>       |               ^
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:3257:12: note: in instantiation of function template specialization 'pcens_model_model_namespace::pcens_model_model::log_prob_impl<false, false, Eigen::Matrix<stan::math::var_value<double>, -1, 1>, Eigen::Matrix<int, -1, 1>, nullptr, nullptr, nullptr>'
#>  requested here
#>  3257 |     return log_prob_impl<propto__, jacobian__>(params_r, par
#> ams_i, pstream);
#>       |            ^
#> /Users/eidesfun/.cmdstan/cmdstan-2.35.0/stan/src/stan/model/model_base_crtp.hpp:98:50: note: in instantiation of function template specialization 'pcens_model_model_namespace::pcens_model_model::log_prob<false, false, stan::math::var_value<double>>' requested here
#>    98 |     return static_cast<const M*>(this)->template log_prob<false, false>(theta,
#>       |                                                  ^
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:2407:3: note: in instantiation of member function 'stan::model::model_base_crtp<pcens_model_model_namespace::pcens_model_model>::log_prob' requested here
#>  2407 |   ~pcens_model_model() {}
#>       |   ^
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:858:47: note: insert an explicit cast to silence this issue
#>   858 |         std::vector<int>{dist_id, primary_id, stan::math::size(params),
#>       |                                               ^~~~~~~~~~~~~~~~~~~~~~~~
#>       |                                               static_cast<int>(       )
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:859:11: error: non-constant-expression cannot be narrowed from type 'size_t' (aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
#>   859 |           stan::math::size(primary_params)}, "assigning variable ids");
#>       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#> /var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.hpp:859:11: note: insert an explicit cast to silence this issue
#>   859 |           stan::math::size(primary_params)}, "assigning variable ids");
#>       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#>       |           static_cast<int>(               )
#> 4 errors generated.
#> make: *** [/var/folders/n9/h_419gjj2mg3d208nplgvbg40000gp/T/RtmpBrnglH/model-11fed4638ba62.o] Error 1
#> Error: An error occured during compilation! See the message above for more information.
```

<sup>Created on 2024-12-10 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by sbfnk**
## Description

This PR closes #177 by replacing `size` with `num_elements`.

## Checklist

- [X] My PR is based on a package issue and I have explicitly linked it.
- [X] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [X] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [X] I have tested my changes locally.
- [ ] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required.
- [ ] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
As noted in the issue I am quite unclear why this didn't work for you in the first place given it works on CI and in epidist. @athowes did you have some m3 issues and did it look the same? Any comment on this 

As this is causing issues regardless of why I am happy to change but can you first update the news file

**Comment by athowes** [comment]
Here is the error I had: https://github.com/epinowcast/epidist/issues/221#issuecomment-2485805430.

It was to do with `stan::math::size` so I think it might be the same but unsure.

**Comment by seabbs** [comment]
I think there isn't a point to forcing people to use a different compiler flag if this is all Mn MacBooks which it sounds like it is so this change to the code makes sense if it works for both of you (and as it works everywhere the old version worked).

**Comment by sbfnk** [comment]
This may also be fixed as of yesterday
https://github.com/stan-dev/math/blob/9bae49db12815e6906765788663ff6b6f04769fc/RELEASE-NOTES.txt#L27

**Comment by seabbs** [comment]
My preference would be to keep using `size` as its shorter and so makes the code easier to parse but its a weak preference

**Comment by sbfnk** [comment]
> add yourself as a contributor in the description
turns out I'm there already

**Review by seabbs — APPROVED** [review]
LGTM

**Comment by sbfnk** [comment]
I still get (almost) the same error with the latest stan math library -- `size_t` has been replaced by `int64_t` but conversion to `int` still yields a warning.

**Pull request merged**
