### PR TITLE
181: pre-assign sizes to variables

### LINKED ISSUE #181: Revert to using size over num_elements in stan code
#177 (fixed in #178) found a type instability when using `size` on M series Macbooks. This seems to have been fixed upstream but the fix isn't with users yet. When it is we should test and revert to using `size()` as the syntax is easier to pass.

### PR DESCRIPTION
**Pull request by sbfnk**
## Description

This PR closes #181.

It fixes the issue by assigning sizes to int first (where type conversion is permitted) and then brace-initialise.

If we agree on the solution I'll add a new news item.

## Checklist

- [X] My PR is based on a package issue and I have explicitly linked it.
- [X] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [X] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [X] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [x] I have added a news item linked to this PR.
- [x] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by sbfnk** [comment]
alternative approach would be to pass these from the function as they're available as data anyway

**Review by seabbs — COMMENTED** [review]
Nice. Do you think this makes the code easier or harder to parse? I think for me maybe it is a little harder like this but only a little

There is also some speed considerations (annoyingly touchstone is down) my assumption is that this approach would be slightly faster due to the reduction in repeated work.

I think with the latter considerations probably worth doing. 

Also quite a few contributions now so I guess its aut time (wow).

**Comment by sbfnk** [comment]
> Nice. Do you think this makes the code easier or harder to parse? I think for me maybe it is a little harder like this but only a little

I would agree with this, and that it's worth doing overall (especially as it won't work on my laptop with the latest version of cmdstan otherwise).

**Comment by sbfnk** [comment]
> Also quite a few contributions now so I guess its aut time (wow).

Half a day of contributions - depends on where you want to set the bar really.

**Comment by seabbs** [comment]
> Half a day of contributions - depends on where you want to set the bar really.

I want to set it very low

**Review by seabbs — APPROVED** [review]
Nice LGTM

**Review by seabbs — APPROVED** [review]

**Pull request merged**
